[tool.poetry]
name = "earlysign"
version = "0.1.0"
description = "Early signs, faster decisions. A Python library for sequential/safe testing (alpha-spending, e-processes, etc.)."
authors = ["Takeshi Teshima <takeshi.78.teshima@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/takeshi-teshima/EarlySign"
repository = "https://github.com/takeshi-teshima/EarlySign"

[tool.poetry.dependencies]
python = ">=3.11"

[tool.poetry.group.examples]
optional = true

[tool.poetry.group.examples.dependencies]
numpy = ">=1.24"
matplotlib = ">=3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Simplify publishing to TestPyPI
[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"
priority = "explicit"
