[project]
name = "earlysign"
version = "0.1.0"
description = "Early signs, faster decisions. A Python library for sequential/safe testing (alpha-spending, e-processes, etc.)."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
# Dependencies required only for running the example plotting scripts / development
# Install with: pip install .[examples]
examples = [
	"numpy>=1.24",
	"matplotlib>=3.7",
]

[tool.uv.dev-dependencies]
# Development-only dependencies for uv (used when developing / running examples)
numpy = ">=1.24"
matplotlib = ">=3.7"
