name: Build and publish docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install documentation build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autodoc-typehints sphinx-copybutton pydata-sphinx-theme sphinx-rtd-theme myst-parser sphinx-autobuild

      - name: Prepare Sphinx source (autogenerate API from package if needed)
        run: |
          set -euo pipefail
          # Prefer an existing Sphinx source dir if present
          if [ -f docs/source/conf.py ] || [ -f docs/conf.py ]; then
            echo "Found existing conf.py — will use docs/ or docs/source/ as-is"
          else
            echo "No conf.py found — generating API stubs into docs/source and creating a minimal conf.py"
            mkdir -p docs/source
            sphinx-apidoc -o docs/source earlysign || true
            cat > docs/source/conf.py <<'PY'
          import os
          import sys
          sys.path.insert(0, os.path.abspath('../..'))

          project = 'EarlySign'
          extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx_autodoc_typehints']
          templates_path = ['_templates']
          exclude_patterns = []
          html_theme = 'pydata_sphinx_theme'
          PY
          fi

      - name: Build HTML
        run: |
          set -euo pipefail
          if [ -f docs/source/conf.py ]; then
            sphinx-build -b html docs/source docs/_build/html -W || true
          elif [ -f docs/conf.py ]; then
            sphinx-build -b html docs docs/_build/html -W || true
          else
            echo "No conf.py found; skipping build"
            exit 0
          fi

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

  publish:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
