name: Publish Python Package with Poetry and uv

on:
  push:
    branches:
      - main # Trigger for TestPyPI
  release:
    types: [published] # Trigger for production PyPI

jobs:
  publish:
    # Dynamically select the environment based on the trigger
    environment: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: pip install uv

    - name: Set up Python and install Poetry
      run: |
        uv venv
        uv pip install poetry
        source .venv/bin/activate
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Configure Poetry for TestPyPI
      # Run only when pushing to a branch
      if: github.event_name == 'push'
      env:
        # Read the secret from the testpypi environment
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: poetry config pypi-token.testpypi $TEST_PYPI_API_TOKEN

    - name: Build package
      run: poetry build

    - name: Publish to TestPyPI
      # Run only when pushing to the main branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: poetry publish -r testpypi

    - name: Publish to PyPI
      # Run only when a release is created
      if: github.event_name == 'release'
      run: poetry publish
