name: Publish Python Package with Poetry and uv

on:
  push:
    branches:
      - main # Trigger for TestPyPI
  release:
    types: [published] # Trigger for production PyPI

jobs:
  publish:
    environment: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
    runs-on: ubuntu-latest
    # OIDC permissions are removed as we are now using tokens

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: pip install uv

    - name: Set up Python and install Poetry
      run: |
        uv venv
        uv pip install poetry
        source .venv/bin/activate
        echo "$VVIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Build package
      run: poetry build

    - name: Publish to PyPI or TestPyPI
      env:
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          poetry publish --username __token__ --password $PYPI_API_TOKEN
        else
          poetry publish -r testpypi --username __token__ --password $TEST_PYPI_API_TOKEN
        fi
